### ISSUE TITLE
CUserCMD issues on the latest update

### ISSUE THREAD

**Issue by elgato69** [maecry/asphyxia-cs2#80] opened 2024-06-04 06:41 UTC
**Describe the bug**
Joining the game with the cheat injected and any modifications to CUserCMD will result in a kick with the following error "Failed to parse user commands"

**To Reproduce**
Enable a feature that modifies CUserCMD such as bhop and go in game

**Expected behavior**
It should not kick you out of the game eksdee

**Additional context**
Problem is definitely related to modifying CUserCMD. Perhaps valvo added some kind of CRC to check for modifications before executing the CMD, but I am not proficient enough with assembly and reversing to fix it myself so in other words please fix it pookie xoxo

**Comment by Exlodium** [comment] 2024-06-04 18:24
Issue can be resolved by adding the correct amount of cached bits, this is not difficult to do. However it takes a bit of time. 
I'll write some functions to make the process easier

**Comment by elgato69** [comment] 2024-06-04 18:40
Can you explain to me the process as high level steps? I'm not asking for code but rather resources and guidance to learn how to fix it and other errors like this by myself in the future.

**Comment by Exlodium** [comment] 2024-06-04 20:06
Pushed an update that might have fixed it.
Didn't have much time to test, but wasn't able to get kicked while testing.
Leaving this open incase the issue isn't fixed

**Comment by nildotdev** [comment] 2024-06-06 13:20
Got kicked after your update, but it definitely happens less now. Not sure what caused it, and I can't really replicate it either. weird

**Comment by Exlodium** [comment] 2024-06-06 14:15
Have you added any additional code or is it happening with the main branch of asphyxia?

**Comment by nildotdev** [comment] 2024-06-06 14:38
Main branch

**Comment by Exlodium** [comment] 2024-06-06 14:59
I might have to rewrite the function.
In protobufs the game adds _has_bits whenever it wants to set forward move or smth.

**Closed** 2024-07-24 18:30 UTC
Labels: bug
